"""应用上下文 - 定义 UI 回调、分组管理等核心接口协议。"""
from typing import Protocol, List, Dict, Any, Optional, Callable, runtime_checkable


@runtime_checkable
class UICallbackProtocol(Protocol):
    def show_error(self, title: str, message: str, parent: Any = None) -> None: ...
    def show_warning(self, title: str, message: str, parent: Any = None) -> None: ...
    def show_info(self, title: str, message: str, parent: Any = None) -> None: ...
    def ask_yes_no(self, title: str, message: str, parent: Any = None) -> bool: ...
    def ask_string(self, title: str, prompt: str, parent: Any = None, initialvalue: str = "") -> Optional[str]: ...
    def ask_open_filename(self, title: str, filetypes: List[tuple]) -> str: ...


@runtime_checkable
class GroupManagerInterface(Protocol):
    data_dir: str
    groups: List[str]
    current_group: str

    def load_groups(self) -> None: ...
    def save_groups(self) -> None: ...
    def add_group(self, group_name: str) -> None: ...
    def new_group(self, parent: Any = None) -> Optional[str]: ...
    def delete_group(self, parent: Any = None) -> Any: ...
    def set_current_group(self, group_name: str) -> None: ...


@runtime_checkable
class UIStateProtocol(Protocol):
    listbox: Any
    listbox_items: List[Dict[str, Any]]
    output_text: Any
    stop_btn: Any
    status_var: Any
    version_var: Any
    group_combo: Any
    search_var: Any

    def get_selected_item(self) -> Optional[Dict[str, Any]]: ...
    def get_selected_items(self) -> List[Dict[str, Any]]: ...
    def set_listbox(self, listbox: Any) -> None: ...
    def set_output_text(self, text_widget: Any) -> None: ...
    def set_stop_button(self, button: Any) -> None: ...
    def set_status_var(self, var: Any) -> None: ...
    def set_version_var(self, var: Any) -> None: ...
    def set_group_combo(self, combo: Any) -> None: ...
    def set_search_var(self, var: Any) -> None: ...
    def set_stop_button_enabled(self, enabled: bool) -> None: ...
    def append_output(self, message: str) -> None: ...
    def clear_output(self) -> None: ...
    def set_status(self, message: str) -> None: ...
    def set_version_info(self, message: str) -> None: ...
    def refresh_group_combo(self, groups: List[str], current_group: str) -> None: ...


@runtime_checkable
class ProcessManagerInterface(Protocol):
    def add_process(self, process: Any, name: str) -> None: ...
    def remove_process(self, process: Any) -> None: ...
    def running_count(self) -> int: ...
    def is_running(self) -> bool: ...
    def get_running_names(self) -> List[str]: ...
    def terminate_all(self) -> List[str]: ...
    def cleanup_dead(self) -> None: ...


@runtime_checkable
class ScriptCollectionProtocol(Protocol):
    def add(self, script: Dict[str, Any]) -> None: ...
    def remove(self, script: Dict[str, Any]) -> None: ...
    def find_by_path(self, storage_path: str) -> Optional[int]: ...
    def update(self, index: int, display: str, group: str) -> None: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...


@runtime_checkable
class AppContext(Protocol):
    data_dir: str
    settings: Dict[str, Any]
    scripts: ScriptCollectionProtocol
    group_manager: GroupManagerInterface
    ui: UICallbackProtocol
    ui_state: UIStateProtocol
    process_manager: ProcessManagerInterface

    def append_output(self, message: str) -> None: ...
    def clear_output(self) -> None: ...
    def set_status(self, message: str) -> None: ...
    def set_version_info(self, message: str) -> None: ...

    def get_selected_item(self) -> Optional[Dict[str, Any]]: ...
    def get_selected_items(self) -> List[Dict[str, Any]]: ...
    def update_listbox(self) -> None: ...
    def refresh_group_combo(self) -> None: ...

    def schedule_callback(self, callback: Callable[[], None]) -> None: ...
    def get_root_window(self) -> Any: ...

    def on_group_changed(self, new_group: str) -> None: ...
    def on_script_selected(self, event: Any) -> None: ...
    def on_close(self) -> None: ...
