from typing import Protocol, List, Dict, Any, Optional, Callable, runtime_checkable


@runtime_checkable
class UICallbackProtocol(Protocol):
    def show_error(self, title: str, message: str, parent: Any = None) -> None: ...
    def show_warning(self, title: str, message: str, parent: Any = None) -> None: ...
    def show_info(self, title: str, message: str, parent: Any = None) -> None: ...
    def ask_yes_no(self, title: str, message: str, parent: Any = None) -> bool: ...
    def ask_string(self, title: str, prompt: str, parent: Any = None, initialvalue: str = "") -> Optional[str]: ...
    def ask_open_filename(self, title: str, filetypes: List[tuple]) -> str: ...


@runtime_checkable
class GroupManagerInterface(Protocol):
    data_dir: str
    groups: List[str]
    current_group: str

    def load_groups(self) -> None: ...
    def save_groups(self) -> None: ...
    def new_group(self, parent: Any = None) -> Optional[str]: ...
    def delete_group(self, parent: Any = None) -> Any: ...
    def set_current_group(self, group_name: str) -> None: ...


@runtime_checkable
class AppContext(Protocol):
    data_dir: str
    settings: Dict[str, Any]
    scripts: List[Dict[str, Any]]
    group_manager: GroupManagerInterface
    ui: UICallbackProtocol

    def append_output(self, message: str) -> None: ...
    def clear_output(self) -> None: ...
    def set_status(self, message: str) -> None: ...
    def set_version_info(self, message: str) -> None: ...

    def get_selected_item(self) -> Optional[Dict[str, Any]]: ...
    def update_listbox(self) -> None: ...
    def scan_data_directory(self) -> None: ...

    def add_script(self, script: Dict[str, Any]) -> None: ...
    def remove_script(self, script: Dict[str, Any]) -> None: ...
    def find_script_by_path(self, storage_path: str) -> Optional[Dict[str, Any]]: ...
    def update_script(self, index: int, display: str, group: str) -> None: ...

    def get_groups(self) -> List[str]: ...
    def get_current_group(self) -> str: ...
    def add_group(self, group: str) -> None: ...

    def get_running_process(self) -> Optional[Any]: ...
    def set_running_process(self, process: Optional[Any]) -> None: ...
    def is_process_stopped(self) -> bool: ...
    def set_process_stopped(self, stopped: bool) -> None: ...
    def set_stop_button_enabled(self, enabled: bool) -> None: ...

    def schedule_callback(self, callback: Callable[[], None]) -> None: ...
    def get_root_window(self) -> Any: ...

    def on_group_changed(self, new_group: str) -> None: ...
    def on_script_selected(self, event: Any) -> None: ...
    def on_close(self) -> None: ...

    def delete_token(self) -> None: ...
    def open_program_dir(self) -> None: ...

    def set_listbox(self, listbox: Any) -> None: ...
    def set_output_text(self, text_widget: Any) -> None: ...
    def set_stop_button(self, button: Any) -> None: ...
    def set_status_var(self, var: Any) -> None: ...
    def set_version_var(self, var: Any) -> None: ...
    def set_group_combo(self, combo: Any) -> None: ...
    def refresh_group_combo(self) -> None: ...
