"""
应用上下文 - 定义核心接口协议（Protocol），实现各模块间的松耦合。

设计原则：
    - 使用 typing.Protocol 定义接口协议，而非具体实现
    - @runtime_checkable 装饰器支持 isinstance() 运行时类型检查
    - 各模块通过协议接口交互，不依赖具体实现类

协议定义：
    UICallbackProtocol：
        UI 回调接口，封装对话框操作
        - show_error / show_warning / show_info：消息对话框
        - ask_yes_no：确认对话框
        - ask_string：输入对话框
        - ask_open_filename：文件选择对话框

    GroupManagerInterface：
        分组管理接口，定义分组 CRUD 操作
        - data_dir / groups / current_group：分组核心属性
        - load_groups / save_groups：持久化
        - add_group / new_group / delete_group：增删操作
        - set_current_group：切换当前分组

    UIStateProtocol：
        UI 状态接口，管理控件引用和状态查询
        - listbox / output_text / stop_btn：核心控件引用
        - status_var / version_var / group_combo / search_var：状态变量
        - get_selected_item(s)：获取选中项
        - append_output / clear_output / set_status：状态更新

    ProcessManagerInterface：
        进程管理接口，管理脚本运行子进程
        - add_process / remove_process：进程注册与注销
        - running_count / is_running / get_running_names：运行状态查询
        - terminate_all / cleanup_dead：进程终止与清理

    ScriptCollectionProtocol：
        脚本集合接口，管理脚本数据列表
        - add / remove / find_by_path / update：集合操作
        - __iter__ / __len__：迭代与长度

    AppContext：
        应用上下文聚合接口，组合以上所有协议
        - 整合 data_dir、settings、scripts、group_manager、ui、ui_state、process_manager
        - 提供统一的输出、状态、选择、刷新方法
        - schedule_callback：线程安全的 UI 回调调度
        - get_root_window：获取根窗口引用

依赖：typing
"""
from typing import Protocol, List, Dict, Any, Optional, Callable, runtime_checkable


@runtime_checkable
class UICallbackProtocol(Protocol):
    def show_error(self, title: str, message: str, parent: Any = None) -> None: ...
    def show_warning(self, title: str, message: str, parent: Any = None) -> None: ...
    def show_info(self, title: str, message: str, parent: Any = None) -> None: ...
    def ask_yes_no(self, title: str, message: str, parent: Any = None) -> bool: ...
    def ask_string(self, title: str, prompt: str, parent: Any = None, initialvalue: str = "") -> Optional[str]: ...
    def ask_open_filename(self, title: str, filetypes: List[tuple]) -> str: ...


@runtime_checkable
class GroupManagerInterface(Protocol):
    data_dir: str
    groups: List[str]
    current_group: str

    def load_groups(self) -> None: ...
    def save_groups(self) -> None: ...
    def add_group(self, group_name: str) -> None: ...
    def new_group(self, parent: Any = None) -> Optional[str]: ...
    def delete_group(self, parent: Any = None) -> Any: ...
    def set_current_group(self, group_name: str) -> None: ...


@runtime_checkable
class UIStateProtocol(Protocol):
    listbox: Any
    listbox_items: List[Dict[str, Any]]
    output_text: Any
    stop_btn: Any
    status_var: Any
    version_var: Any
    group_combo: Any
    search_var: Any

    def get_selected_item(self) -> Optional[Dict[str, Any]]: ...
    def get_selected_items(self) -> List[Dict[str, Any]]: ...
    def set_listbox(self, listbox: Any) -> None: ...
    def set_output_text(self, text_widget: Any) -> None: ...
    def set_stop_button(self, button: Any) -> None: ...
    def set_status_var(self, var: Any) -> None: ...
    def set_version_var(self, var: Any) -> None: ...
    def set_group_combo(self, combo: Any) -> None: ...
    def set_search_var(self, var: Any) -> None: ...
    def set_stop_button_enabled(self, enabled: bool) -> None: ...
    def append_output(self, message: str) -> None: ...
    def clear_output(self) -> None: ...
    def set_status(self, message: str) -> None: ...
    def set_version_info(self, message: str) -> None: ...
    def refresh_group_combo(self, groups: List[str], current_group: str) -> None: ...


@runtime_checkable
class ProcessManagerInterface(Protocol):
    def add_process(self, process: Any, name: str) -> None: ...
    def remove_process(self, process: Any) -> None: ...
    def running_count(self) -> int: ...
    def is_running(self) -> bool: ...
    def get_running_names(self) -> List[str]: ...
    def terminate_all(self) -> List[str]: ...
    def cleanup_dead(self) -> None: ...


@runtime_checkable
class ScriptCollectionProtocol(Protocol):
    def add(self, script: Dict[str, Any]) -> None: ...
    def remove(self, script: Dict[str, Any]) -> None: ...
    def find_by_path(self, storage_path: str) -> Optional[int]: ...
    def update(self, index: int, display: str, group: str) -> None: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...


@runtime_checkable
class AppContext(Protocol):
    data_dir: str
    settings: Dict[str, Any]
    scripts: ScriptCollectionProtocol
    group_manager: GroupManagerInterface
    ui: UICallbackProtocol
    ui_state: UIStateProtocol
    process_manager: ProcessManagerInterface

    def append_output(self, message: str) -> None: ...
    def clear_output(self) -> None: ...
    def set_status(self, message: str) -> None: ...
    def set_version_info(self, message: str) -> None: ...

    def get_selected_item(self) -> Optional[Dict[str, Any]]: ...
    def get_selected_items(self) -> List[Dict[str, Any]]: ...
    def update_listbox(self) -> None: ...
    def refresh_group_combo(self) -> None: ...

    def schedule_callback(self, callback: Callable[[], None]) -> None: ...
    def get_root_window(self) -> Any: ...

    def on_group_changed(self, new_group: str) -> None: ...
    def on_script_selected(self, event: Any) -> None: ...
    def on_close(self) -> None: ...
